import type { Metadata } from 'next';
import '@/styles/global.scss';
import StoreProvider from '@/components/provider/StoreProvider';
import { spoqa } from '@/styles/fonts';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={spoqa.variable}>
        <StoreProvider> {children}</StoreProvider>
      </body>
    </html>
  );
}
